name: TDR Tag build release deploy to intg
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  pre-deploy:
     uses: nationalarchives/tdr-github-actions/.github/workflows/ecs_build.yml@main
     with:
        repo-name: tdr-draft-metadata-validator
        image-name: draft-metadata-validator
     secrets:
        MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
        WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
  deploy:
    uses: nationalarchives/tdr-github-actions/.github/workflows/lambda_deploy.yml@main
    with:
      lambda-name: draft-metadata-validator
      deployment-package: draft-metadata-validator.jar
      environment: ${{ github.event.inputs.environment }}
      to-deploy: ${{ github.event.inputs.to-deploy }}
      image-name: draft-metadata-validator
    secrets:
      ACCOUNT_NUMBER: ${{ secrets.ACCOUNT_NUMBER }}
      MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
