name: TDR Tag build release and deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  pre-deploy:
    uses: nationalarchives/tdr-github-actions/.github/workflows/ecs_build.yml@main
    with:
      repo-name: tdr-draft-metadata-validator
      image-name: draft-metadata-validator
    secrets:
      MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
  deploy-env-version:
     uses: nationalarchives/tdr-github-actions/.github/workflows/ecr_image_env_tag.yml@version-tag-ecr
     with:
       repo-name: tdr-draft-metadata-validator
       environment: intg
       image-name: draft-metadata-validator
       to-deploy: ${{ needs.pre-deploy.outputs.next-version }}
     secrets:
       ACCOUNT_NUMBER: ${{ secrets.ACCOUNT_NUMBER }}
       MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
       WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
       SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  deploy:
    needs: 
     - pre-deploy
     - deploy-env-version
    uses: nationalarchives/tdr-github-actions/.github/workflows/lambda_deploy.yml@version-tag-ecr
    with:
      lambda-name: draft-metadata-validator
      deployment-package: draft-metadata-validator.jar
      environment: intg
      to-deploy: ${{ needs.pre-deploy.outputs.next-version }}
      image-name: draft-metadata-validator
    secrets:
      ACCOUNT_NUMBER: ${{ secrets.ACCOUNT_NUMBER }}
      MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
