name: TDR Tag build release and deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build-image:
    uses: nationalarchives/tdr-github-actions/.github/workflows/ecs_build.yml@main
    with:
      repo-name: tdr-draft-metadata-validator
      image-name: draft-metadata-validator
    secrets:
      MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
  deploy:
    needs: pre-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gh workflow run deploy.yml -f environment=intg -f to-deploy=${{ needs.build-image.outputs.next-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
