name: TDR Tag build release and deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build-image:
    uses: nationalarchives/tdr-github-actions/.github/workflows/ecs_build.yml@main
    with:
      repo-name: tdr-draft-metadata-validator
      image-name: draft-metadata-validator
    secrets:
      MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
  tag-ecr-image:
    needs:
      - build-image
    uses: nationalarchives/tdr-github-actions/.github/workflows/ecr_image_tag.yml.yml@main
    with:
      repo-name: tdr-draft-metadata-validator
      tag: intg
      image-name: draft-metadata-validator
      to-deploy: ${{ needs.build-image.outputs.next-version }}
    secrets:
      MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  deploy:
    needs:
      - tag-ecr-image
      - build-image
    uses: nationalarchives/tdr-github-actions/.github/workflows/lambda_deploy.yml@main
    with:
      lambda-name: draft-metadata-validator
      deployment-package: draft-metadata-validator.jar
      environment: intg
      to-deploy: ${{ needs.build-image.outputs.next-version }}
      image-name: draft-metadata-validator
    secrets:
      ACCOUNT_NUMBER: ${{ secrets.ACCOUNT_NUMBER }}
      MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
