name: TDR Deploy Lambda
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        options:
          - intg
          - staging
          - prod
        default: 'intg'
      to-deploy:
        description: 'Version to deploy'
        required: true
      lambda-name:
        description: 'Lambda name'
        required: true
      deployment-package:
        description: 'Deployment package name'
        required: true

run-name: Deploying ${{inputs.lambda-name}} ${{inputs.to-deploy}} to ${{inputs.environment}}
permissions:
  id-token: write
  contents: write
jobs:
  deploy:
    uses: nationalarchives/tdr-github-actions/.github/workflows/lambda_deploy.yml@main
    with:
      lambda-name: ${{ github.event.inputs.lambda-name }}
      deployment-package: ${{ github.event.inputs.deployment-package }}
      environment: ${{ github.event.inputs.environment }}
      to-deploy: ${{ github.event.inputs.to-deploy }}
    secrets:
      ACCOUNT_NUMBER: ${{ secrets.ACCOUNT_NUMBER }}
      MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
