name: TDR Deploy Draft Metadata Validator Lambda
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        options:
          - intg
          - staging
          - prod
          - test
        default: 'intg'
      to-deploy:
        description: 'Version to deploy'
        required: true

run-name: Deploying Draft Metadata Validator Lambda ${{inputs.to-deploy}} to ${{inputs.environment}}
permissions:
  id-token: write
  contents: write
jobs:
  tag-ecr-image:
    uses: nationalarchives/tdr-github-actions/.github/workflows/ecr_image_tag.yml@main
    with:
      tag: ${{inputs.environment}}
      image-name: draft-metadata-validator
      to-deploy: ${{ inputs.to-deploy }}
    secrets:
      MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  deploy:
    needs:
      - tag-ecr-image
    uses: nationalarchives/tdr-github-actions/.github/workflows/lambda_deploy.yml@main
    with:
      lambda-name: draft-metadata-validator
      deployment-package: draft-metadata-validator.jar
      environment: ${{inputs.environment}}
      to-deploy: ${{ inputs.to-deploy }}
      image-name: draft-metadata-validator
    secrets:
      ACCOUNT_NUMBER: ${{ secrets.ACCOUNT_NUMBER }}
      MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
