name: TDR Run Lambda Tests
on:
  push:
    branches-ignore:
      - main
      - release-*
permissions:
  id-token: write
  contents: read
jobs:
  test:
    uses: nationalarchives/tdr-github-actions/.github/workflows/tdr_test.yml@main
    with:
      repo-name: tdr-draft-metadata-validator
      test-command: |
        sbt scalafmtCheckAll test
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
